### ISSUE TITLE
Doesnt go past startup

### ISSUE THREAD

**Issue by flyhtz** [codeuk/TrollWare#1]
i run the program and it says  "[+] Startup!
than goes on to say:

Traceback (most recent call last):
  File "C:\Users\...\Downloads\TrollWare-main\TrollWare-main\main.py", line 1348, in <module>
    start()
  File "C:\Users\...\Downloads\TrollWare-main\TrollWare-main\main.py", line 1340, in start
    Logging.Discord.FetchTokens()
  File "C:\Users\...\Downloads\TrollWare-main\TrollWare-main\main.py", line 438, in FetchTokens
    if response.json()['premium_type'] == 2:
KeyError: 'premium_type'

have done my fair share of debugging but nothing works.

**Comment by codeuk** [comment]
Have you installed all the needed prerequisites? *pip install -r requirements.txt*

**Comment by flyhtz** [comment]
I have, i've also tried to convert it to an exe and see if it would run than but the same error keeps popping up.

**Comment by flyhtz** [comment]
what my cmd says:

   ▄▄▄▄▀ █▄▄▄▄ ████▄ █    █      ▄ ▄   ██   █▄▄▄▄ ▄███▄   
▀▀▀ █    █  ▄▀ █   █ █    █     █   █  █ █  █  ▄▀ █▀   ▀  
    █    █▀▀▌  █   █ █    █    █ ▄   █ █▄▄█ █▀▀▌  ██▄▄    
   █     █  █  ▀████ ███▄ ███▄ █  █  █ █  █ █  █  █▄   ▄▀ 
  ▀        █             ▀    ▀ █ █ █     █   █   ▀███▀   
          ▀                      ▀ ▀     █   ▀            
                                        ▀         
             [CREATED BY: github.com/codeuk]                   

    
 [+] Startup!

Traceback (most recent call last):
  File "C:\Users\dabom\Downloads\TrollWare-main\TrollWare-main\main.py", line 1348, in <module>
    start()
  File "C:\Users\dabom\Downloads\TrollWare-main\TrollWare-main\main.py", line 1340, in start
    Logging.Discord.FetchTokens()
  File "C:\Users\dabom\Downloads\TrollWare-main\TrollWare-main\main.py", line 438, in FetchTokens
    if response.json()['premium_type'] == 2:
KeyError: 'premium_type'


I think I might have the wrong version of python installed, could u inform me of the version u are using?

**Comment by codeuk** [comment]
I've been using version 3.9.7 when running & testing it. Let me know how it goes when you use 3.9.7?

**Comment by flyhtz** [comment]
I have installed windows freshly and than installed python 3.9.7, it still gives me the same error as before. i have no idea what is casuing this problem

**Comment by flyhtz** [comment]
the entire class of discord isnt working, if u delete it the rest of the programs work, i think it has something to do with the json things (i dont understand it that well) and if u dont have chrome (like me) the rest of the program also doesnt work.

**Comment by codeuk** [comment]
Apologies for not responding right away, it seems some others who don't have certain modules installed get the same error, I'm looking into it!
