### ISSUE TITLE
Error Line 67  filelink = f"[File]({resp['data']['downloadPage']})" 

### ISSUE THREAD

**Issue by SkidedUser** [codeuk/TrollWare#11]
```
  File "main.py", line 67
    filelink = f"[File]({resp['data']['downloadPage']})"
                                                       ^
SyntaxError: invalid syntax
```

Please can you help me?

**Comment by SkidedUser** [comment]
System Specs:

[upload.systems](https://uploadi.ng/O6o6dv6H)

**Comment by SkidedUser** [comment]
I have python 2 and 3 installed too. Currently using python 2.

**Comment by codeuk** [comment]
SOLVED ON DISCORD - Person was using python 2 and eventually tried with python 3 and it worked.
