### ISSUE TITLE
Credits !!

### ISSUE THREAD

**Issue by KanekiWeb** [codeuk/TrollWare#14]
## Where is my credits ?

- I'm still looking for my credits for some of the code you took from [https://github.com/KanekiWeb/Powerfull-Token-Stealer/blob/main/main.py](https://github.com/KanekiWeb/Powerfull-Token-Stealer/blob/main/main.py), Please add my credits ^^

**Comment by codeuk** [comment]
DM me on Discord - doop#0001, someone I worked on the project with must've used your code as their own - Apologies.
