### ISSUE TITLE
the system information not sending

### ISSUE THREAD

**Issue by RAZ321** [codeuk/TrollWare#16]
the system information not sending, it's only the account embed

**Comment by xharky** [comment]
Yeah for me Account embed sending but the System not

**Comment by RAZ321** [comment]
The problem comes from embeds.append(embed) at line 542, the embed "embeds" does not add the embed "embed" and therefore the embed system is not sent. Only the account embed sending.

**Comment by codeuk** [comment]
Does your account have billing enabled? it might be a problem with that - also check the switches (true/false settings) and make sure the sendsystem is turned to true. thanks.

**Comment by RAZ321** [comment]
All switches are turned to true, so the problem comes from the embed. I try to find the problem but it didn't work. Pls can you find the bug and fix it ?

**Comment by codeuk** [comment]
Are you on windows?

**Comment by codeuk** [comment]
@RAZ321 why did you use my whole logger in your repository without even asking me first?

**Comment by RAZ321** [comment]
I just forked it
