### ISSUE TITLE
Compiling to EXE breaks.

### ISSUE THREAD

**Issue by YumYummity** [codeuk/TrollWare#17]
Using PyInstaller to compile the file (with all the modules and requirements installed) breaks it, it just spam sends
"**New TrollWare Connection**  ||@everyone||"
and doesn't move on.

Command used:
`pyinstaller main.py`

**Comment by codeuk** [comment]
I haven't focused on making the program eligible for exe compilation. When a program needs this many modules it's hard for it to be compatible with the compilation software (in this case pyinstaller). I'll look into making it work soon
