### ISSUE TITLE
Setup Not working for me.

### ISSUE THREAD

**Issue by Jacobtuffman** [codeuk/TrollWare#22]
Originally, when I ran setup.bat I got This:
![Untitled](https://user-images.githubusercontent.com/98600021/172052677-4b0dc959-3d5f-4d4d-b8a0-f4ec3fdaebec.png)
And then CMD would close.

Now, I update pip and restart setup.bat and get this:
![wcqecqwd](https://user-images.githubusercontent.com/98600021/172052818-0f5c1520-1dd4-41b1-aec3-4ca018783185.png)
Then, it closes again.

Any help much appreciated.

**Comment by Jacobtuffman** [comment]
I accidentally used the wrong python version. I have updated now I'm getting a new problem:
![image](https://user-images.githubusercontent.com/98600021/172056450-0fb236cd-582e-433b-b0c6-5a6cd8703212.png)

**Comment by codeuk** [comment]
Your python version doesn't have the permissions to use PIP, this is not a
troll ware issue and it's with your installation of python.
