### ISSUE TITLE
error when running.

### ISSUE THREAD

**Issue by 5mf** [codeuk/TrollWare#3]
I'm trying to run the bot first of all with runrat = True | And i get this error : 
`Traceback (most recent call last):
  File "C:\Users\andre\OneDrive\Desktop\TrollWare-main\main.py", line 1364, in <module>  
    start()
  File "C:\Users\andre\OneDrive\Desktop\TrollWare-main\main.py", line 1356, in start     
    Logging.Discord.FetchTokens()
  File "C:\Users\andre\OneDrive\Desktop\TrollWare-main\main.py", line 450, in FetchTokens
    if response.json()['premium_type'] == 2:
KeyError: 'premium_type' `

^^ This. I have install the req , put the webhook and bot token. Help?

**Comment by codeuk** [comment]
I have already mentioned this error in the readme, if I come back to this project I'll issue a common fix.

You need to remove the lines which produce the errors but leave in the function definitions/names and the return line, and change the return line to anything but the variable which you have deleted.

If you don't understand / keep getting different errors, just reply back here and I'll make a fix within the next couple of days, as I'm quite busy at the moment.

**Comment by 5mf** [comment]
I'm not really into python , started to learn it recently 😅. And i tried to do what you said and still getting errors ( new ones ). I would appreciate if you would come with a fix in a few days. Thank you, Happy Holidays!

**Comment by 5mf** [comment]
Hello! Still gonna post a fix any time soon ? Thanks!

**Comment by codeuk** [comment]
Sorry, I've just started a new MIT course which has taken up lots of my, usually, free time.
You should probably just look for another project similar to this as it's overcomplicated for what it is, and unmaintained; as I'm now working on another project releasing soon.

Thanks.
