### ISSUE TITLE
Error TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by lol12121121** [codeuk/TrollWare#4]
I try to solve it but nothing works for me, also download the main.py returned and without anything modified and I still get that erro
![Screenshot_27](https://user-images.githubusercontent.com/96712746/148627474-5c9da92e-32c2-420d-b2f5-8cb48de2e202.png)
r

**Comment by codeuk** [comment]
Hi, you can fix this by indenting the return line 2 times, I'm also updating the source to fix this, although there are many other errors.
