### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xharky** [codeuk/TrollWare#8]
Command raised an exception: UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3080: character maps to <undefined> idk how to fix xdd

**Comment by codeuk** [comment]
I'm going to need a more detailed error. Could you atleast screenshot the command window?

Thanks.

**Comment by xharky** [comment]
This is the error 
Mabeay you can make a example Video how to do it
Thx.

**Comment by xharky** [comment]
![Screenshot (149)](https://user-images.githubusercontent.com/90693180/151683308-6d4bc043-f02d-4cbf-93a1-32ce5fe6d4b3.png)

**Comment by 94q** [comment]
`pip install charmap`
`pip install discord` ( if not installed )

^^ this should work.

**Comment by xharky** [comment]
What Version of charmap

**Comment by xharky** [comment]
so the Account() funktion is sending but the system() not sending per webhook but idk why

**Comment by codeuk** [comment]
Apologies! it seems I didn't get notifications for this thread - Please redownload the repository and try again.

If errors continue to persist, again please leave a detail of your error/exception or a screenshot of your console terminal.

Thanks.

**Comment by xharky** [comment]
I sended a Screenshot

**Comment by 94q** [comment]
i say you should reinstall discord.py

`pip uninstall discord`
`pip install discord`

`python3.6 -m pip install discord.py` change 3.6 with the version of python you have installed and added to path. If you dont have python added to path please reinstall python and at the setup installer make sure to press "Add to PATH". I recommend using python 3.10.2 Just my opinion. Thanks!

**Comment by xharky** [comment]
![image](https://user-images.githubusercontent.com/90693180/152180229-6880c782-6643-4cd5-aff1-21968751e13a.png)

**Comment by xharky** [comment]
what version i need

**Comment by codeuk** [comment]
I'm looking into this now, as I've never experienced this error on my own system - It's clearly a unicode byte decoding error but the character it's referencing isn't in the program **(

0x272 / &#626;)**.

If/When I find a fix or find out it's a problem with your system I'll make a commit but until then I'll continue the thread.

**Comment by xharky** [comment]
Ok
