### ISSUE TITLE
[ not an issue ]

### ISSUE THREAD

**Issue by 94q** [codeuk/TrollWare#9]
After i runned setup.bat, i would get errors about packages that i didnt install. I recommend you to add to setup.bat : 
`pip install pypiwin32`
`pip install opencv-python`
`easy_install pycrypto` **OR** `pip install pycrypto` ( i keep getting errors when trying to install and im using python 3.7.8 )
^^ If you still get crypto error. Just remove line 23 (`from Crypto.Cipher import AES`) and it will work. 
After installing all the packages and removing line 23, my trollware was working fine with no errors or bugs.

**Comment by codeuk** [comment]
Thanks, will make a commit for this now.
